<a href="https://colab.research.google.com/github/pauarmentaa/Extraccion-de-Datos/blob/main/Actividad_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [3]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
#df

In [4]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

In [5]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

## **FILTROS**

**FILTRO 1**

Este primer filtro decidi aplicarlo por el nombre del vendedor, en este caso de "DIEGO ARMANDO LEON DURAN" para así conocer que ventas tuvo durante ese año y posteriormente poder aplicar metodos estadísticos para un mejor conocimiento u entendimiento de los datos.

In [6]:
#Filtro por objeto 
filtro1=df[df["NOMBRE_VENDEDOR"] == "DIEGO ARMANDO LEON DURAN"]
filtro1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,F38005,2022-04-27,DIEGO ARMANDO LEON DURAN,MARCEGAGLIA MEXICO,5,TUE00261,"TUB INOX 3/8""ØX395MM CIR/ALETA 8500W230V",6300.00,694.60,694.60,31500.00,3472.99,5605.40,28027.01
580,F38141,2022-05-12,DIEGO ARMANDO LEON DURAN,DISMAPP PRODUCTOS IMPRESOS,2,BC00027,BC PLANA 132MMX280MM 2000W240V OCTAGO-TJ,2750.00,797.54,797.54,5500.00,1595.08,1952.46,3904.92
731,F38459,2022-06-24,DIEGO ARMANDO LEON DURAN,MEXICANA DE INGENIERIA Y MAQUINARIA,3,CAE00011,"CAE 9.4MMØx2""LONG ESC90°150W 220V Ext22""",375.00,0.00,122.35,1125.00,367.04,252.65,757.96
851,F38665,2022-07-26,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50
1296,F39592,2022-11-16,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50

In [44]:
filtro1.to_csv("Filtro1.csv")

**FILTRO 2**

En este segundo filtro en la parte de filas consecutivas decidi aplicarlo para conocer las ventas que tuvo la empresa en el mes de Enero de 2022, es por ello que esta filtrado desde la fila 0 hasta la 119.

In [21]:
#Filtro por filas
filtro2= df.iloc[0:119,: ]           #Filas consecutivas
#filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas 
filtro2

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,F37242,2022-01-31,ALFREDO CANELA,RAUL PULIDO AMBRIZ,1,TUA00401,"TUB INOX 7/16""ØX26CM 2700W 240V ""M"" BUSH",1250.00,281.94,281.94,1250.00,281.94,968.06,968.06
115,F37243,2022-01-31,LETICIA RAMIREZ HERNANDEZ,SCIMPLA,4,CAS00066,CAS INOX 12MMØX90MM 220W 110V EXT.15CMS,617.00,0.00,67.22,2468.00,268.86,549.79,2199.14
116,F37249,2022-01-31,AARON NUÑO CORDOVA,INGENIERIA DE PLASTICOS E IMPRESIONES,2,BB00077,BB INOX 40MMØX60MM 300W 240V EXT.30CM,510.00,0.00,37.76,1020.00,75.53,472.24,944.47
117,F37250,2022-01-31,DIEGO ARMANDO LEON DURAN,MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACC...,1,TUS00052,"TUB INOX 1/4""Øx280mm 200W 120V RECTA ZAP",197.50,13.38,13.38,197.50,13.38,184.12,184.12
118,F37255,2022-02-01,DIEGO ARMANDO LEON DURAN,INMOBILIARIA MONTAÑA,1,TU5/16X230MM,"TUBULAR J"" 5/16"" 230MM 4500W 220V""",1000.00,0.00,226.23,1000.00,226.23,773.77,773.77

In [45]:
filtro2.to_csv("Filtro2.csv")

**FILTRO 3**

En este tercer filtro en la parte de filas NO consecutivas decidi aplicarlo para conocer las ventas que tuvo la empresa en el mes de Enero de 2022, es por ello que esta filtrado desde la fila 0 hasta la 119 pero solo con las columnas de interes, que sería la fecha, el vendedor, la cantidad vendida, que artículo fue y su precio.

In [26]:
#Filtro por columnas
#filtro3=df.iloc[ 0:119 , 1:7]       #Columnas consecutivas 
filtro3=df.iloc[ 0:119 , [1,2,4,6,7]]  #Columnas no consecutivas 
filtro3

,FECHA_DOC,NOMBRE_VENDEDOR,CANT,DESCR,PRECIO_UNITARIO
0,2022-01-05,LETICIA RAMIREZ HERNANDEZ,1,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48
1,2022-01-05,LETICIA RAMIREZ HERNANDEZ,1,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05
2,2022-01-05,DIEGO ARMANDO LEON DURAN,7,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61
3,2022-01-05,DIEGO ARMANDO LEON DURAN,1,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00
4,2022-01-05,LETICIA RAMIREZ HERNANDEZ,2,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41
...,...,...,...,...,...
114,2022-01-31,ALFREDO CANELA,1,"TUB INOX 7/16""ØX26CM 2700W 240V ""M"" BUSH",1250.00
115,2022-01-31,LETICIA RAMIREZ HERNANDEZ,4,CAS INOX 12MMØX90MM 220W 110V EXT.15CMS,617.00
116,2022-01-31,AARON NUÑO CORDOVA,2,BB INOX 40MMØX60MM 300W 240V EXT.30CM,510.00
117,2022-01-31,DIEGO ARMANDO LEON DURAN,1,"TUB INOX 1/4""Øx280mm 200W 120V RECTA ZAP",197.50
118,2022-02-01,DIEGO ARMANDO LEON DURAN,1,"TUBULAR J"" 5/16"" 230MM 4500W 220V""",1000.00

In [46]:
filtro3.to_csv("Filtro3.csv")

**FILTRO 4**

En este cuarto filtro como primer punto establecí como indice el nombre del cliente, para posteriormente poder filtrar por dos clientes, en este caso, "PÚBLICO EN GENERAL" y "CEREALES Y PASTAS" y su SUBTOTAL_PARTIDA que es el monto total de lo que le han comprado a la empresa Calor y Control.

In [ ]:
#Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

In [30]:
df1= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx', index_col=3)
df1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
NOMBRE_CLIENTE,,,,,,,,,,,,,
PÚBLICO EN GENERAL,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
JUAN ANTONIO RESENDIZ UGALDE,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
ANA BARBARA CRUZ PALACIOS,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
OMAR RODRIGUEZ GOMEZ,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
PÚBLICO EN GENERAL,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
LUIS ENRIQUE PATIÑO PEREZ,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
LUIS ENRIQUE PATIÑO PEREZ,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
SEVEN DAYS ALL SPORT,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
REVUELTA MONTECARLO,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
CPEG SOLUTIONS,F39838,2022-12-23,AARON NUÑO CORDOVA,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [31]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro4=df1.loc[["PÚBLICO EN GENERAL","CEREALES Y PASTAS"], ["SUBTOTAL_PARTIDA"]]
filtro4

                    SUBTOTAL_PARTIDA
NOMBRE_CLIENTE
PÚBLICO EN GENERAL            434.48
PÚBLICO EN GENERAL            344.83
PÚBLICO EN GENERAL            474.14
PÚBLICO EN GENERAL           2420.00
PÚBLICO EN GENERAL           1044.00
...                              ...
CEREALES Y PASTAS            5412.50
CEREALES Y PASTAS            4956.00
CEREALES Y PASTAS            4880.00
CEREALES Y PASTAS           16152.50
CEREALES Y PASTAS            4880.00

[121 rows x 1 columns]

In [47]:
filtro4.to_csv("Filtro4.csv")

**FILTRO 5**

En este quinto filtro se nos muestran los primeros 10 datos del archivo 'Detalle precios y productos fabricados 2022.xlsx' de la empresa Calor y Control.

In [32]:
#Filtro por cabecera
filtro5=df.head(10)
filtro5

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11

In [48]:
filtro5.to_csv("Filtro5.csv")

**FILTRO 6**

En este sexto filtro decidi tomar la columna de "SUBTOTAL_PARTIDA" y filtrar en la columna aquellos totales que sean mayores o iguales a 50,000 pesos.

In [41]:
#Filtro por comparacion
filtro6=df[df["SUBTOTAL_PARTIDA"] >= 50000]
filtro6

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
204,F37443,2022-02-23,DIEGO ARMANDO LEON DURAN,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,0.00,254.34,52200.0,9156.17,1195.66,43043.83
394,F37758,2022-03-29,ALFREDO CANELA,ALYEX ALUMINUM,18,TUE00319,"TUB INCOLOY 7/16""ØX305CM 2300W380V ESPEC",4150.00,0.00,714.20,74700.0,12855.68,3435.80,61844.32
403,F37777,2022-03-31,ALFREDO CANELA,CLAVOS NACIONALES C.N,60,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,340.80,340.80,77959.2,20448.01,958.52,57511.19
503,F37977,2022-04-25,ALFREDO CANELA,ALYEX ALUMINUM,18,TUE00319,"TUB INCOLOY 7/16""ØX305CM 2300W380V ESPEC",4150.00,714.20,714.20,74700.0,12855.68,3435.80,61844.32
533,F38047,2022-04-29,ALFREDO CANELA,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,35,ECQ-00972,"TUB. ENCAPSULADA 5/16Øx780mm 1500W 240V""",1475.30,335.51,335.51,51635.5,11742.95,1139.79,39892.55
615,F38221,2022-05-24,LETICIA RAMIREZ HERNANDEZ,TERMOFORMATEC,60,CAS00080,CAS INOX 18.5MMØX205MM 950W 440V EXT30CM,1296.00,0.00,244.07,77760.0,14643.92,1051.93,63116.08
654,F38312,2022-06-03,ALFREDO CANELA,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,266.04,266.04,52200.0,9577.26,1183.97,42622.74
1076,F39139,2022-09-23,ALFREDO CANELA,CARCOUSTICS INDUSTRIAL DE MEXICO,18,BS00006,BP S/BLINDA 300MMX698MM 2500W 230V 18BA,7780.00,816.73,1743.86,70020.0,16025.97,6036.14,53994.03
1077,F39139,2022-09-23,ALFREDO CANELA,CARCOUSTICS INDUSTRIAL DE MEXICO,18,BS00008,BP S/BLINDA 300MMX698MM 2000W 230V 18BA,7780.00,930.34,2064.16,70020.0,19187.82,5715.84,50832.18
1104,F39201,2022-09-30,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,0.00,1721.28,75476.0,6885.12,17147.72,68590.88
1226,F39436,2022-10-28,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,1721.28,1721.28,75476.0,6885.12,17147.72,68590.88

In [49]:
filtro6.to_csv("Filtro6.csv")

**FILTRO 7**

En este septimo filtro decidi tomar de igual forma la columna de "SUBTOTAL_PARTIDA" y filtrar en la columna aquellos totales que sean mayores o iguales a 50,000 pesos, pero esta vez incluyendo la fecha en la que se creo o se genero el documento.

In [42]:
#Filtro Y
filtro7=df[(df["SUBTOTAL_PARTIDA"] >= 50000) & (df["FECHA_DOC"] == "2022-09-23")]
filtro7

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1076,F39139,2022-09-23,ALFREDO CANELA,CARCOUSTICS INDUSTRIAL DE MEXICO,18,BS00006,BP S/BLINDA 300MMX698MM 2500W 230V 18BA,7780.0,816.73,1743.86,70020.0,16025.97,6036.14,53994.03
1077,F39139,2022-09-23,ALFREDO CANELA,CARCOUSTICS INDUSTRIAL DE MEXICO,18,BS00008,BP S/BLINDA 300MMX698MM 2000W 230V 18BA,7780.0,930.34,2064.16,70020.0,19187.82,5715.84,50832.18

In [50]:
filtro7.to_csv("Filtro7.csv")

**FILTRO 8**

En este octavo filtro decidi tomar de igual forma la columna de "SUBTOTAL_PARTIDA" y filtrar en la columna aquellos totales que sean mayores o iguales a 50,000 pesos. Pero esta vez filtra aquellos documentos en que su fecha de creación haya sido "2022-09-23" no importa su monto y aquellos documentos que en la columna de "SUBTOTAL_PARTIDA" su total haya sido mayor o igual a 50,000 pesos no importa su fecha.

In [43]:
#Filtro o (una u otra)
filtro8=df[(df["SUBTOTAL_PARTIDA"] >= 50000) | (df["FECHA_DOC"] == "2022-09-23")]
filtro8

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
204,F37443,2022-02-23,DIEGO ARMANDO LEON DURAN,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,0.00,254.34,52200.00,9156.17,1195.66,43043.83
394,F37758,2022-03-29,ALFREDO CANELA,ALYEX ALUMINUM,18,TUE00319,"TUB INCOLOY 7/16""ØX305CM 2300W380V ESPEC",4150.00,0.00,714.20,74700.00,12855.68,3435.80,61844.32
403,F37777,2022-03-31,ALFREDO CANELA,CLAVOS NACIONALES C.N,60,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,340.80,340.80,77959.20,20448.01,958.52,57511.19
503,F37977,2022-04-25,ALFREDO CANELA,ALYEX ALUMINUM,18,TUE00319,"TUB INCOLOY 7/16""ØX305CM 2300W380V ESPEC",4150.00,714.20,714.20,74700.00,12855.68,3435.80,61844.32
533,F38047,2022-04-29,ALFREDO CANELA,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,35,ECQ-00972,"TUB. ENCAPSULADA 5/16Øx780mm 1500W 240V""",1475.30,335.51,335.51,51635.50,11742.95,1139.79,39892.55
615,F38221,2022-05-24,LETICIA RAMIREZ HERNANDEZ,TERMOFORMATEC,60,CAS00080,CAS INOX 18.5MMØX205MM 950W 440V EXT30CM,1296.00,0.00,244.07,77760.00,14643.92,1051.93,63116.08
654,F38312,2022-06-03,ALFREDO CANELA,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,266.04,266.04,52200.00,9577.26,1183.97,42622.74
1066,F39128,2022-09-23,LETICIA RAMIREZ HERNANDEZ,FINCOMBER GRUPO EMPRESARIAL,1,BB2X2ST,"BOQUILLA 2X2"" 350W 240V""",462.00,220.00,220.00,462.00,220.00,242.00,242.00
1067,F39130,2022-09-23,LETICIA RAMIREZ HERNANDEZ,INSTITUTO DEL DEPORTE Y LA RECREACION DEL ESTA...,1,TUA00459,"TUB INOX 7/16""ØX42CM 2000W 240V ""M"" BUSH",1165.95,345.97,345.97,1165.95,345.97,819.98,819.98
1068,F39131,2022-09-23,LETICIA RAMIREZ HERNANDEZ,INSTITUTO DEL DEPORTE Y LA RECREACION DEL ESTA...,1,TUA00459,"TUB INOX 7/16""ØX42CM 2000W 240V ""M"" BUSH",1165.95,0.00,345.97,1165.95,345.97,819.98,819.98
1069,F39133,2022-09-23,LETICIA RAMIREZ HERNANDEZ,ERICKA TERESA HERNANDEZ ORTIZ,4,CAS00051,"CAR INOX 3/8""Øx26CMS LONG 1200W 127V CAB",763.00,0.00,71.72,3052.00,286.90,691.28,2765.10
1070,F39133,2022-09-23,LETICIA RAMIREZ HERNANDEZ,ERICKA TERESA HERNANDEZ ORTIZ,4,CBS00007,"CBS INOX 3/8"" DE ØX61CMTS1200W127V TF",845.00,0.00,167.31,3380.00,669.24,677.69,2710.76
1071,F39134,2022-09-23,LETICIA RAMIREZ HERNANDEZ,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,685.68,685.68,1615.00,685.68,929.32,929.32
1072,F39135,2022-09-23,LETICIA RAMIREZ HERNANDEZ,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,685.68,685.68,1615.00,685.68,929.32,929.32
1073,F39136,2022-09-23,LETICIA RAMIREZ HERNANDEZ,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,685.68,685.68,1615.00,685.68,929.32,929.32
1074,F39137,2022-09-23,LETICIA RAMIREZ HERNANDEZ,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,685.68,685.68,1615.00,685.68,929.32,929.32
1075,F39138,2022-09-23,LETICIA RAMIREZ HERNANDEZ,VICTOR HUGO CASTELLANOS NUÑEZ,2,TP0011,"TERMOPAR CERAMICO T/K"" LONG 12"" CAL 8""",485.00,144.40,144.40,970.00,288.80,340.60,681.20
1076,F39139,2022-09-23,ALFREDO CANELA,CARCOUSTICS INDUSTRIAL DE MEXICO,18,BS00006,BP S/BLINDA 300MMX698MM 2500W 230V 18BA,7780.00,816.73,1743.86,70020.00,16025.97,6036.14,53994.03
1077,F39139,2022-09-23,ALFREDO CANELA,CARCOUSTICS INDUSTRIAL DE MEXICO,18,BS00008,BP S/BLINDA 300MMX698MM 2000W 230V 18BA,7780.00,930.34,2064.16,70020.00,19187.82,5715.84,50832.18
1078,F39142,2022-09-23,LETICIA RAMIREZ HERNANDEZ,MAYRA HUERTA MARTINEZ,4,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,125.00,48.20,48.20,500.00,192.79,76.80,307.21
1104,F39201,2022-09-30,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,0.00,1721.28,75476.00,6885.12,17147.72,68590.88
1226,F39436,2022-10-28,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,1721.28,1721.28,75476.00,6885.12,17147.72,68590.88

In [51]:
filtro8.to_csv("Filtro8.csv")

**FILTRO 9**

En este noveno filtro decidi tomar de igual forma la columna de "SUBTOTAL_PARTIDA" y filtrar en la columna aquellos totales que sean mayores o iguales a 50,000 pesos, pero esta vez filtra aquellos documentos que son mayores o iguales a 50,000 pesos y que no esten en la fecha de "2022-09-23" .

In [40]:
#Filtro not
filtro9=df[~(df["SUBTOTAL_PARTIDA"] <= 50000) & ~(df["FECHA_DOC"] == "2022-09-23")]
filtro9

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
204,F37443,2022-02-23,DIEGO ARMANDO LEON DURAN,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,0.00,254.34,52200.0,9156.17,1195.66,43043.83
394,F37758,2022-03-29,ALFREDO CANELA,ALYEX ALUMINUM,18,TUE00319,"TUB INCOLOY 7/16""ØX305CM 2300W380V ESPEC",4150.00,0.00,714.20,74700.0,12855.68,3435.80,61844.32
403,F37777,2022-03-31,ALFREDO CANELA,CLAVOS NACIONALES C.N,60,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,340.80,340.80,77959.2,20448.01,958.52,57511.19
503,F37977,2022-04-25,ALFREDO CANELA,ALYEX ALUMINUM,18,TUE00319,"TUB INCOLOY 7/16""ØX305CM 2300W380V ESPEC",4150.00,714.20,714.20,74700.0,12855.68,3435.80,61844.32
533,F38047,2022-04-29,ALFREDO CANELA,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,35,ECQ-00972,"TUB. ENCAPSULADA 5/16Øx780mm 1500W 240V""",1475.30,335.51,335.51,51635.5,11742.95,1139.79,39892.55
615,F38221,2022-05-24,LETICIA RAMIREZ HERNANDEZ,TERMOFORMATEC,60,CAS00080,CAS INOX 18.5MMØX205MM 950W 440V EXT30CM,1296.00,0.00,244.07,77760.0,14643.92,1051.93,63116.08
654,F38312,2022-06-03,ALFREDO CANELA,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,266.04,266.04,52200.0,9577.26,1183.97,42622.74
1104,F39201,2022-09-30,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,0.00,1721.28,75476.0,6885.12,17147.72,68590.88
1226,F39436,2022-10-28,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,1721.28,1721.28,75476.0,6885.12,17147.72,68590.88

In [52]:
filtro9.to_csv("Filtro9.csv")